const SAMPLE_FOOD_DATA = [
  {
    product: "Strawberry",
    productSearch: "Starwberry",
    color: "red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: "2022-08-18",
  },
  {
    product: "Cabbage",
    productSearch: "Cabbage (Purple)",
    color: "purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: "2022-08-18",
  },
  {
    product: "Pepper",
    productSearch: "Pepper (Green)",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-18",
  },
  {
    product: "Strawberry",
    productSearch: "Starwberry",
    color: "red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: "2022-08-17",
  },
  {
    product: "Kale",
    productSearch: "Kale",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-17",
  },
  {
    product: "Lettuce",
    productSearch: "Lettuce (Green)",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-17",
  },
  {
    product: "Cabbage",
    productSearch: "Cabbage (Purple)",
    color: "purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: "2022-08-17",
  },
  {
    product: "Pepper",
    productSearch: "Pepper (Green)",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-17",
  },
  {
    product: "Banana",
    productSearch: "Banana",
    color: "yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: "2022-08-16",
  },
  {
    product: "Bell Pepper",
    productSearch: "Bell Pepper (Orange)",
    color: "orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: "2022-08-16",
  },
  {
    product: "Beet",
    productSearch: "Beet",
    color: "red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: "2022-08-16",
  },
  {
    product: "Apple",
    productSearch: "Apple (Red)",
    color: "red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: "2022-08-14",
  },
  {
    product: "Mango",
    productSearch: "Mango",
    color: "orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: "2022-08-14",
  },
  {
    product: "Eggplant",
    productSearch: "Eggplant",
    color: "purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: "2022-08-14",
  },
  {
    product: "Kumquat",
    productSearch: "Kumquat",
    color: "orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: "2022-08-13",
  },
  {
    product: "Kumquat",
    productSearch: "Kumquat",
    color: "orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: "2022-08-13",
  },
  {
    product: "Lettuce",
    productSearch: "Lettuce (Green)",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-13",
  },
  {
    product: "Mango",
    productSearch: "Mango",
    color: "orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: "2022-08-13",
  },
  {
    product: "Squash",
    productSearch: "Squash (Yellow)",
    color: "yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: "2022-08-13",
  },
  {
    product: "Carrot",
    productSearch: "Carrot (Yellow)",
    color: "yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: "2022-08-12",
  },
  {
    product: "Onion",
    productSearch: "Onion (Green)",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-11",
  },
  {
    product: "Eggplant",
    productSearch: "Eggplant",
    color: "purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: "2022-08-11",
  },
  {
    product: "Blackberry",
    productSearch: "Blackberry",
    color: "purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: "2022-08-10",
  },
  {
    product: "Cabbage",
    productSearch: "Cabbage (Purple)",
    color: "purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: "2022-08-10",
  },
  {
    product: "Onion",
    productSearch: "Onion (White)",
    color: "white",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: "2022-08-10",
  },
  {
    product: "Mango",
    productSearch: "Mango",
    color: "orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: "2022-08-10",
  },
  {
    product: "Radish",
    productSearch: "Radish (White)",
    color: "white",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: "2022-08-10",
  },
  {
    product: "Mushroom",
    productSearch: "Mushroom",
    color: "white",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: "2022-08-10",
  },
  {
    product: "Strawberry",
    productSearch: "Starwberry",
    color: "red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: "2022-08-09",
  },
  {
    product: "Kale",
    productSearch: "Kale",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-07",
  },
  {
    product: "Lettuce",
    productSearch: "Lettuce (Green)",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-07",
  },
  {
    product: "Cabbage",
    productSearch: "Cabbage (Purple)",
    color: "purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: "2022-08-07",
  },
  {
    product: "Pepper",
    productSearch: "Pepper (Green)",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-06",
  },
  {
    product: "Banana",
    productSearch: "Banana",
    color: "yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: "2022-08-06",
  },
  {
    product: "Bell Pepper",
    productSearch: "Bell Pepper (Orange)",
    color: "orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: "2022-08-01",
  },
  {
    product: "Beet",
    productSearch: "Beet",
    color: "red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: "2022-08-01",
  },
  {
    product: "Apple",
    productSearch: "Apple (Red)",
    color: "red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: "2022-07-28",
  },
  {
    product: "Mango",
    productSearch: "Mango",
    color: "orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: "2022-07-28",
  },
  {
    product: "Eggplant",
    productSearch: "Eggplant",
    color: "purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: "2022-07-28",
  },
  {
    product: "Kumquat",
    productSearch: "Kumquat",
    color: "orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: "2022-07-28",
  },
  {
    product: "Kumquat",
    productSearch: "Kumquat",
    color: "orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: "2022-07-28",
  },
  {
    product: "Lettuce",
    productSearch: "Lettuce (Green)",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-07-28",
  },
  {
    product: "Mango",
    productSearch: "Mango",
    color: "orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: "2022-07-28",
  },
  {
    product: "Squash",
    productSearch: "Squash (Yellow)",
    color: "yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: "2022-07-28",
  },
  {
    product: "Carrot",
    productSearch: "Carrot (Yellow)",
    color: "yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: "2022-07-28",
  },
  {
    product: "Onion",
    productSearch: "Onion (Green)",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-07-27",
  },
  {
    product: "Eggplant",
    productSearch: "Eggplant",
    color: "purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: "2022-07-27",
  },
  {
    product: "Blackberry",
    productSearch: "Blackberry",
    color: "purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: "2022-07-27",
  },
  {
    product: "Cabbage",
    productSearch: "Cabbage (Purple)",
    color: "purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: "2022-07-26",
  },
  {
    product: "Onion",
    productSearch: "Onion (White)",
    color: "white",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: "2022-07-26",
  },
  {
    product: "Mango",
    productSearch: "Mango",
    color: "orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: "2022-07-26",
  },
  {
    product: "Radish",
    productSearch: "Radish (White)",
    color: "white",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: "2022-07-26",
  },
  {
    product: "Mushroom",
    productSearch: "Mushroom",
    color: "white",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: "2022-07-25",
  },
];

export default SAMPLE_FOOD_DATA;
