const SAMPLE_FOOD_DB = [
  {
    product: "Strawberry",
    productSearch: "Strawberry",
    color: "red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: "2022-08-18",
  },
  {
    product: "Cabbage",
    productSearch: "Cabbage (Purple)",
    color: "purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: "2022-08-18",
  },
  {
    product: "Cabbage",
    productSearch: "Cabbage (Green)",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-18",
  },
  {
    product: "Cabbage",
    productSearch: "Cabbage (Red)",
    color: "red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: "2022-08-18",
  },
  {
    product: "Kale",
    productSearch: "Kale",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-17",
  },
  {
    product: "Watermelon",
    productSearch: "Watermelon",
    color: "red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: "2022-08-18",
  },
  {
    product: "Lettuce",
    productSearch: "Lettuce (Green)",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-17",
  },
  {
    product: "Banana",
    productSearch: "Banana",
    color: "yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: "2022-08-16",
  },
  {
    product: "Bell Pepper",
    productSearch: "Bell Pepper (Orange)",
    color: "orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: "2022-08-16",
  },
  {
    product: "Beet",
    productSearch: "Beet",
    color: "red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: "2022-08-16",
  },
  {
    product: "Pepper",
    productSearch: "Pepper (Green)",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-18",
  },
  {
    product: "Apple",
    productSearch: "Apple (Red)",
    color: "red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: "2022-08-14",
  },
  {
    product: "Mango",
    productSearch: "Mango",
    color: "orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: "2022-08-14",
  },
  {
    product: "Eggplant",
    productSearch: "Eggplant",
    color: "purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: "2022-08-14",
  },
  {
    product: "Kumquat",
    productSearch: "Kumquat",
    color: "orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: "2022-08-13",
  },
  {
    product: "Squash",
    productSearch: "Squash (Yellow)",
    color: "yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: "2022-08-13",
  },
  {
    product: "Carrot",
    productSearch: "Carrot (Yellow)",
    color: "yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: "2022-08-12",
  },
  {
    product: "Onion",
    productSearch: "Onion (Green)",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-11",
  },
  {
    product: "Blackberry",
    productSearch: "Blackberry",
    color: "purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: "2022-08-10",
  },
  {
    product: "Grape",
    productSearch: "Grape (Purple)",
    color: "purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: "2022-08-10",
  },
  {
    product: "Grape",
    productSearch: "Grape (Green)",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-11",
  },
  {
    product: "Onion",
    productSearch: "Onion (White)",
    color: "white",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: "2022-08-10",
  },
  {
    product: "Raspberry",
    productSearch: "Raspberry",
    color: "red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: "2022-08-14",
  },
  {
    product: "Radish",
    productSearch: "Radish (White)",
    color: "white",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: "2022-08-10",
  },
  {
    product: "Kiwi",
    productSearch: "Kiwi",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-11",
  },
  {
    product: "Mushroom",
    productSearch: "Mushroom",
    color: "white",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: "2022-08-10",
  },
  {
    product: "Avocado",
    productSearch: "Avocado",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-10",
  },
  {
    product: "Pineapple",
    productSearch: "Pineapple",
    color: "yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: "2022-08-12",
  },
  {
    product: "Apricot",
    productSearch: "Apricot",
    color: "yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: "2022-08-12",
  },
  {
    product: "Blureberry",
    productSearch: "Blueberry",
    color: "purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: "2022-08-18",
  },
  {
    product: "Lime",
    productSearch: "Lime",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-10",
  },
  {
    product: "Cauliflower",
    productSearch: "Cauliflower",
    color: "white",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: "2022-08-10",
  },
  {
    product: "Idaho Potato",
    productSearch: "Idaho Potato",
    color: "white",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: "2022-08-10",
  },
  {
    product: "Honeydew",
    productSearch: "HoneyDew",
    color: "green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: "2022-08-10",
  },
  {
    product: "Coconut",
    productSearch: "Coconut",
    color: "white",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: "2022-08-10",
  },
];

export default SAMPLE_FOOD_DB;
