const masterFoodLibrary = [
  {
    product: "Açai",
    productSearch: "Açai",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Almond",
    productSearch: "Almond",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Artichoke",
    productSearch: "Artichoke (Purple)",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Arugula",
    productSearch: "Arugula",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Asparagus",
    productSearch: "Asparagus (Green)",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Asparagus",
    productSearch: "Asparagus, Purple",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Asparagus",
    productSearch: "Asparagus (White)",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Avocado",
    productSearch: "Avocado",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Banana",
    productSearch: "Banana",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },
  {
    product: "Basil",
    productSearch: "Basil (Purple)",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Bell Pepper",
    productSearch: "Pepper, Bell (Purple)",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Bell Pepper",
    productSearch: "Pepper, Bell (Red)",
    color: "Red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: null,
  },
  {
    product: "Bitter Melon",
    productSearch: "Bitter Melon",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },

  {
    product: "Blackberry",
    productSearch: "Blackberry",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Blueberry",
    productSearch: "Blueberry",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Boisenberry",
    productSearch: "Boisenberry",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Broccoli",
    productSearch: "Broccoli (Purple)",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Cabbage",
    productSearch: "Cabbage (Green)",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Carrot",
    productSearch: "Carrot (Purple)",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Carrot",
    productSearch: "Carrot (White)",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Cashew",
    productSearch: "Cashew",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Cassava",
    productSearch: "Cassava",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Cauliflower",
    productSearch: "Cauliflower (Yellow)",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },
  {
    product: "Cauliflower",
    productSearch: "Cauliflower (Purple)",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Celery",
    productSearch: "Celery",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Chayote",
    productSearch: "Chayote",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Cherimoya",
    productSearch: "Cherimoya",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Chili Pepper",
    productSearch: "Pepper, Chili (Red)",
    color: "Red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: null,
  },
  {
    product: "Cilantro",
    productSearch: "Cilantro",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Cherry",
    productSearch: "Cherry (Red)",
    color: "Red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: null,
  },
  {
    product: "Chlorella",
    productSearch: "Chlorella",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Citron",
    productSearch: "Citron",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },
  {
    product: "Coconut",
    productSearch: "Coconut",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Corn",
    productSearch: "Corn (Yellow)",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },
  {
    product: "Couscous",
    productSearch: "Couscous",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Cranberry",
    productSearch: "Cranberry",
    color: "Red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: null,
  },
  {
    product: "Cucumber",
    productSearch: "Cucumber (Green)",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Dandelion Green",
    productSearch: "Dandelion, Greens",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Dill",
    productSearch: "Dill",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Dragonfruit",
    productSearch: "Dragonfruit (White)",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Dragonfruit",
    productSearch: "Dragonfruit (Purple)",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Dragonfruit",
    productSearch: "Dragonfruit (Red)",
    color: "Red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: null,
  },
  {
    product: "Durian",
    productSearch: "Durian",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },
  {
    product: "Eggplant",
    productSearch: "Eggplant",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Fiddlehead Fern",
    productSearch: "Fiddlehead Fern",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Fig",
    productSearch: "Fig (Purple)",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Grape",
    productSearch: "Grape (Red)",
    color: "Red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: null,
  },
  {
    product: "Grapefruit",
    productSearch: "Grapefruit (White)",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },
  {
    product: "Grape",
    productSearch: "Grape (Purple)",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Grapefruit",
    productSearch: "Grapefruit (Pink)",
    color: "Red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: null,
  },
  {
    product: "Green Tea",
    productSearch: "Green Tea",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Guava",
    productSearch: "Guava (Pink)",
    color: "Red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: null,
  },
  {
    product: "Jackfruit",
    productSearch: "Jackfruit",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },
  {
    product: "Jalapeño Pepper",
    productSearch: "Pepper, Jalapeño",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Jicama",
    productSearch: "Jicama",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Kiwano Melon",
    productSearch: "Kiwano Melon",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Lamb's Quarters",
    productSearch: "Lamb's Quarters",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Leek",
    productSearch: "Leek",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Lemon",
    productSearch: "Lemon",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },
  {
    product: "Lemongrass",
    productSearch: "Lemongrass",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Lettuce",
    productSearch: "Lettuce (Green)",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Lime",
    productSearch: "Lime",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Kale",
    productSearch: "Kale (Green)",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },

  {
    product: "Kale",
    productSearch: "Kale (Purple)",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Lotus Root",
    productSearch: "Lotus Root",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Microgreens",
    productSearch: "Microgreens (Green)",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Mint",
    productSearch: "Mint",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Moringa",
    productSearch: "Moringa",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Nopal",
    productSearch: "Nopal/Cactus",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Okra",
    productSearch: "Okra (Green)",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Papaya",
    productSearch: "Papaya",
    color: "Orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: null,
  },
  {
    product: "Parsley",
    productSearch: "Parsley",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Passionfruit",
    productSearch: "Passionfruit",
    color: "Orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: null,
  },
  {
    product: "Pomegranate",
    productSearch: "Pomegranate",
    color: "Red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: null,
  },
  {
    product: "Prune",
    productSearch: "Prune",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Quince",
    productSearch: "Quince",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },
  {
    product: "Radish",
    productSearch: "Radish (Red)",
    color: "Red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: null,
  },
  {
    product: "Raisin",
    productSearch: "Raisin",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Raspberry",
    productSearch: "Raspberry (Red)",
    color: "Red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: null,
  },
  {
    product: "Raspberry",
    productSearch: "Raspberry (Yellow)",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },
  {
    product: "Rhubarb",
    productSearch: "Rhubarb",
    color: "Red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: null,
  },
  {
    product: "Rosemary",
    productSearch: "Rosemary",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Sage",
    productSearch: "Sage",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Seaweed",
    productSearch: "Seaweed",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Spinach",
    productSearch: "Spinach",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Spirulina",
    productSearch: "Spirulina",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Sprouts",
    productSearch: "Sprouts (Green)",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Squash",
    productSearch: "Squash (Yellow)",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },
  {
    product: "Starfruit",
    productSearch: "Starfruit",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },
  {
    product: "Stinging Nettle",
    productSearch: "Stinging Nettle",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Strawberry",
    productSearch: "Strawberry",
    color: "Red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: null,
  },
  {
    product: "Sunchoke",
    productSearch: "Sunchoke",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Sweet Potato",
    productSearch: "Sweet Potato (Purple)",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Taro",
    productSearch: "Taro (Purple)",
    color: "Purple",
    textHex: "#7471E7",
    fillHex: "#4B37A8",
    date: null,
  },
  {
    product: "Taro",
    productSearch: "Taro (White)",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Thyme",
    productSearch: "Thyme",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Tomato",
    productSearch: "Tomato (Red)",
    color: "Red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: null,
  },
  {
    product: "Tomato",
    productSearch: "Tomato (Yellow)",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },
  {
    product: "Apricot",
    productSearch: "Apricot (Yellow)",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },
  {
    product: "Lentil",
    productSearch: "Lentil (Yellow)",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },

  {
    product: "Melon",
    productSearch: "Melon (Yellow)",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },
  {
    product: "Watermelon",
    productSearch: "Watermelon (Yellow)",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },
  {
    product: "Raisin",
    productSearch: "Raisin (Yellow)",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },

  {
    product: "Cherry",
    productSearch: "Cherry (Yellow)",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },
  {
    product: "Squash",
    productSearch: "Squash (Orange)",
    color: "Orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: null,
  },
  {
    product: "Apricot",
    productSearch: "Apricot (Orange)",
    color: "Orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: null,
  },
  {
    product: "Cantaloupe",
    productSearch: "Cantaloupe",
    color: "Orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: null,
  },
  {
    product: "Carrot",
    productSearch: "Carrot (Orange)",
    color: "Orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: null,
  },
  {
    product: "Turmeric",
    productSearch: "Turmeric",
    color: "Orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: null,
  },
  {
    product: "Cloudberry",
    productSearch: "Cloudberry",
    color: "Orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: null,
  },
  {
    product: "Groundcherry",
    productSearch: "Groundcherry",
    color: "Orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: null,
  },
  {
    product: "Kumquat",
    productSearch: "Kumquat",
    color: "Orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: null,
  },
  {
    product: "Orange",
    productSearch: "Orange",
    color: "Orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: null,
  },
  {
    product: "Tangerine",
    productSearch: "Tangerine",
    color: "Orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: null,
  },

  {
    product: "Sweet Potato",
    productSearch: "Sweet Potato (Orange)",
    color: "Orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: null,
  },
  {
    product: "Persimmon",
    productSearch: "Persimmon",
    color: "Orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: null,
  },
  {
    product: "Pumpkin",
    productSearch: "Pumpkin",
    color: "Orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: null,
  },
  {
    product: "Loquat",
    productSearch: "Loquat",
    color: "Orange",
    textHex: "#FD8F52",
    fillHex: "#FD8F52",
    date: null,
  },
  {
    product: "Onion",
    productSearch: "Onion (White)",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Cabbage",
    productSearch: "Cabbage (White)",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Radish",
    productSearch: "Radish (White)",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Garlic",
    productSearch: "Garlic",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Heart of Palm",
    productSearch: "Heart of Palm",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Horseradish",
    productSearch: "Horseradish",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Lychee",
    productSearch: "Lychee",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Potato",
    productSearch: "Potato",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Millet",
    productSearch: "Millet",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Ginger",
    productSearch: "Ginger",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Rambutan",
    productSearch: "Rambutan",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Kiwi",
    productSearch: "Kiwi",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Romanesco",
    productSearch: "Romanesco",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },

  {
    product: "Mushroom",
    productSearch: "Mushroom",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Pineapple",
    productSearch: "Pineapple",
    color: "Yellow",
    textHex: "#FFBB1C",
    fillHex: "#F9C449",
    date: null,
  },
  {
    product: "Cauliflower",
    productSearch: "Cauliflower (White)",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Tofu",
    productSearch: "Tofu",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Honeydew",
    productSearch: "Honey Dew",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Guava",
    productSearch: "Guava (White)",
    color: "White",
    textHex: "#97906E",
    fillHex: "#F2EDCF",
    date: null,
  },
  {
    product: "Wasabi",
    productSearch: "Wasabi",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Watercress",
    productSearch: "Watercress",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Watermelon",
    productSearch: "Watermelon (Red)",
    color: "Red",
    textHex: "#F94D4D",
    fillHex: "#F94D4D",
    date: null,
  },
  {
    product: "Wheatgrass",
    productSearch: "Wheatgrass",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
  {
    product: "Zucchini",
    productSearch: "Zucchini",
    color: "Green",
    textHex: "#479D45",
    fillHex: "#6AAB9C",
    date: null,
  },
];

export default masterFoodLibrary;
