import Head from "next/head";
import PageContainer from "../components/PageContainer";

import HomeImages from "../components/HomeImages";
import HomeGraphContainer from "../components/HomeGraphContainer";
import HomeCenterContainer from "../components/HomeCenterContainer";
import HomeStatsContainer from "../components/HomeStatsContainer";

const Home = () => {
  return (
    <PageContainer isLanding={true}>
      <Head>
        <title>Glow</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeImages />
      <HomeGraphContainer />
      <HomeCenterContainer />
      <HomeStatsContainer />
    </PageContainer>
  );
};

export default Home;
