import Head from "next/head";
import PageContainer from "../components/PageContainer";
import Heading1 from "../components/Heading1";
import Heading2 from "../components/Heading2";
import LargeLinkedButton from "../components/LargeLinkedButton";

import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <PageContainer isLanding={true}>
      <Head>
        <title>Glow</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img className={styles.grapes} src="/landing/grapes-home.png" />
      <img className={styles.carrot1} src="/stats/goldenCarrot.png" />
      <img className={styles.carrot2} src="/stats/goldenCarrot.png" />
      <img className={styles.carrot5} src="/stats/goldenCarrot.png" />
      <div className={styles.container}>
        <div className={styles.headings}>
          <Heading1>
            Welcome to <span className={styles.glowText}>Glow</span>
          </Heading1>
          <Heading2>
            The fun and effective way to document all the healthy, colorful
            foods we eat!
          </Heading2>
          <Heading2>
            Start tracking your Rainbow diet and collecting Golden Carrots
            today!
          </Heading2>
        </div>
        <div className={styles.buttonPair}>
          <img className={styles.carrot3} src="/stats/goldenCarrot.png" />
          <img className={styles.carrot4} src="/stats/goldenCarrot.png" />
          <LargeLinkedButton href="/create-account" isLanding={true}>
            Get Started
          </LargeLinkedButton>
          <LargeLinkedButton href="/sign-in" isLanding={true}>
            I Already Have An Account
          </LargeLinkedButton>
        </div>
      </div>
      <img className={styles.rainbow} src="/landing/rainbow-home.png" />
    </PageContainer>
  );
};

export default Home;
