import Head from "next/head";
import PageContainer from "../components/PageContainer";
import Heading1 from "../components/Heading1";
import Heading2 from "../components/Heading2";
import LargeLinkedButton from "../components/LargeLinkedButton";

import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <PageContainer isLanding={true}>
      <Head>
        <title>Glow</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img className={styles.grapes} src="/landing/grapes-home.png" />
      <Heading1>
        Welcome to <span className={styles.glowText}>Glow</span>
      </Heading1>
      <Heading2>
        The fun and effective way to document all the healthy, colorful foods we
        eat!
      </Heading2>
      <Heading2>Start tracking your Rainbow diet today!</Heading2>
      <div className={styles.buttonPair}>
        <LargeLinkedButton href="/create-account" isLanding={true}>
          Create Account
        </LargeLinkedButton>
        <LargeLinkedButton href="/sign-in" isLanding={true}>
          Log In
        </LargeLinkedButton>
      </div>
      <img className={styles.rainbow} src="/landing/rainbow-home.png" />
    </PageContainer>
  );
};

export default Home;
